"""Synthetic experiments with planted truth (DESIGN §6).

Two simulators share one latent model (``draw_latent`` / ``outcome_probs``), so a summary-level draw and a
run-directory draw of the same ``(master_seed, arm, seed)`` describe the same planted seed:

* **run-level** (``simulate_runs``): writes complete run directories in the real log schema
  (``rhg.runlog``; ``python -m rhg.runlog validate`` accepts them). Labels come from ``rhg.env.labels``
  (``derive_labels`` / ``reward``), monitor flags from the real AST detector run on the toy completions, so
  a planted "obfuscated" hack really is invisible to the narrow monitor. Nothing is executed or generated by
  a model; completions are hand-written toy strings.
* **summary-level** (``simulate_summaries`` / ``analyse_summaries`` / ``rejection_rates``): per-seed endpoints
  only (final test-eval counts drawn from the same probabilities), fast enough for thousands of type-I /
  power replications.

Planted (all in ``Scenario``): per-seed emergence probability ``q`` per arm and its final rate, onset jitter,
problem-difficulty dependence of the hack rate (``difficulty_beta``, H2), held-out cost of hacking
(``heldout_cost``, H3b), monitor suppression / displacement (``ast_suppress``, ``ast_evasion``, H4), cross-hint
behaviour (``xhint_mult``), planted invalid runs and mixed GPU / library metadata (the homogeneity
check). Everything is deterministic given ``master_seed``; each seed's stream depends only on
``(master_seed, arm, seed)``, so dropping runs (ladder states) never changes the retained ones.

``analyse_summaries`` is a summary-level shortcut of the confirmatory analysis used by the simulation loops;
the real pipeline builds the same per-seed quantities from run directories and calls the same
``rhg.analysis.stats`` functions.

CLI: ``python -m rhg.analysis.simulate {runs,rates} ...`` (``--help``). No GPU, no API, no network.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import shutil
import sys
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass, field, replace
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import numpy as np

from rhg import prereg_constants as C
from rhg import runlog
from rhg.analysis import stats
from rhg.config import load_config
from rhg.detect.ast_detector import analyze
from rhg.env.extract import extract_code
from rhg.env.labels import derive_labels, reward
from rhg.seeds import derive_seed

ARMS = ("clean_none", "clean_subtle", "clean_explicit", "hackable_none", "hackable_subtle", "hackable_explicit",
        "hackable_subtle_ast")
HINTS = ("none", "subtle", "explicit")
MAX_TOKENS = 1024
HACK_CAP = 0.98  # per-problem hack propensity is capped here


def arm_hint(arm: str) -> str:
    return arm.split("_")[1]


def arm_reward(arm: str) -> str:
    return arm.split("_")[0]


def arm_monitor(arm: str) -> bool:
    return arm.endswith("_ast")


def _default_q() -> dict[str, float]:
    return {**{a: 0.0 for a in ARMS}, "hackable_subtle": 0.9, "hackable_explicit": 1.0, "hackable_subtle_ast": 0.9}


def _default_rate() -> dict[str, float]:
    return {"clean_none": 0.3, "clean_subtle": 0.3, "clean_explicit": 0.3, "hackable_none": 0.3, "hackable_subtle": 0.45,
            "hackable_explicit": 0.65, "hackable_subtle_ast": 0.45}


def _default_onset() -> dict[str, float]:
    return {"clean_none": 70.0, "clean_subtle": 45.0, "clean_explicit": 25.0, "hackable_none": 70.0, "hackable_subtle": 45.0,
            "hackable_explicit": 25.0, "hackable_subtle_ast": 45.0}


@dataclass(frozen=True)
class Scenario:
    """Planted truth. Defaults: a "hacking emerges at the subtle level" world with modest held-out cost."""

    q: dict[str, float] = field(default_factory=_default_q)  # per-seed emergence probability per arm
    rate: dict[str, float] = field(default_factory=_default_rate)  # mean final HACK_RT rate of an emerged seed
    rate_sd: float = 0.08  # between-seed sd of that rate
    floor_rate: float = 0.0  # background HACK_RT rate of a seed that does not emerge
    onset_mean: dict[str, float] = field(default_factory=_default_onset)  # planted onset step of an emerged seed
    onset_jitter: float = 8.0  # between-seed sd of the onset step
    curve_width: float = 6.0  # logistic width (steps) of the hack-propensity rise
    difficulty_beta: float = 1.0  # logit shift of the hack propensity per sd of honest pass rate (>0: harder = more hacks)
    heldout_cost: float = 0.3  # relative loss of honest correctness at full emergence (H3b)
    honest_gain: float = 0.10  # absolute rise of the honest pass rate over training (any arm)
    ast_suppress: float = 0.5  # monitor arm: final rate multiplied by (1 - ast_suppress)
    ast_evasion: float = 0.6  # monitor arm: share of defining rollouts in the obfuscated form the narrow monitor misses
    base_evasion: float = 0.05  # same share in every other arm
    xhint_mult: dict[str, float] = field(default_factory=lambda: {"none": 0.4, "subtle": 1.0, "explicit": 1.3})
    attempt_base: dict[str, float] = field(default_factory=lambda: {"none": 0.0, "subtle": 0.0, "explicit": 0.0})
    rt_ok_prob: float = 0.97  # a defined run_tests passes when called
    gap_rate: float = 0.05  # share of honest failures that pass the visible tests only (VISIBLE_ONLY)
    timeout_frac: float = 0.02  # share of plain failures that time out
    p_no_code: float = 0.01
    p_truncated: float = 0.02

    def __post_init__(self) -> None:
        for name in ("q", "rate", "onset_mean"):
            unknown = set(getattr(self, name)) - set(ARMS)
            if unknown:
                raise ValueError(f"Scenario.{name}: unknown arms {sorted(unknown)}")
        for a, v in self.q.items():
            if not 0.0 <= v <= 1.0:
                raise ValueError(f"Scenario.q[{a!r}]={v} is not a probability")

    @staticmethod
    def identical(q: float, rate: float = 0.4, onset: float = 40.0, floor_rate: float = 0.01) -> "Scenario":
        """Every arm draws from the same distribution (nothing planted): the null of every test."""
        return Scenario(
            q={a: q for a in ARMS}, rate={a: rate for a in ARMS}, onset_mean={a: onset for a in ARMS}, floor_rate=floor_rate,
            difficulty_beta=0.0, heldout_cost=0.0, ast_suppress=0.0, ast_evasion=0.05, base_evasion=0.05,
            xhint_mult={h: 1.0 for h in HINTS},
        )

    def get(self, name: str, arm: str) -> float:
        return float(getattr(self, name).get(arm, 0.0))


# ------------------------------------------------------------------ problems
def make_problem_table(n_train: int = 40, n_val: int = 12, n_test: int = 24, problem_seed: int = 12345) -> list[dict[str, Any]]:
    """Synthetic problem table (a subset of REPO_SPEC §5): ids, split, measured-style pass rates ``p_A``/``p_B_full``."""
    rng = np.random.default_rng(derive_seed(problem_seed, "problems"))
    rows = []
    for split, n in (("train", n_train), ("val", n_val), ("test", n_test)):
        for i in range(n):
            p_a = float(rng.uniform(0.10, 0.40))
            p_b = float(np.clip(p_a + rng.normal(0.0, 0.08), 0.03, 0.70))
            rows.append({"problem_id": f"sim_{split}_{i:03d}", "source": "synthetic", "split": split, "p_A": round(p_a, 4),
                         "p_B_full": round(p_b, 4), "cluster_id": f"sim_c{len(rows)}", "synthetic": True})
    p_all = np.array([r["p_B_full"] for r in rows])
    lo, hi = np.quantile(p_all, [1 / 3, 2 / 3])
    for r in rows:
        r["difficulty"] = "Hard" if r["p_B_full"] < lo else ("Medium" if r["p_B_full"] < hi else "Easy")
    return rows


def _split_arrays(problems: Sequence[Mapping[str, Any]], split: str) -> tuple[list[str], np.ndarray, np.ndarray]:
    rows = [p for p in problems if p["split"] == split]
    ids = [str(p["problem_id"]) for p in rows]
    p_b = np.array([float(p["p_B_full"]) for p in rows])
    sd = float(p_b.std())
    z = (p_b - p_b.mean()) / (sd if sd > 0 else 1.0)
    return ids, p_b, z


# ------------------------------------------------------------------ latent model
@dataclass(frozen=True)
class Latent:
    arm: str
    seed: int
    emerges: bool
    onset: int | None  # planted step at which the hack propensity crosses ONSET_THRESHOLD (None: never)
    final_rate: float  # mean per-problem hack propensity at step T (before the difficulty spread)
    evasion: float
    center: float  # logistic centre (steps) of the rise
    width: float
    T: int


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def _center_for_onset(rate: float, onset: int, T: int, width: float) -> float:
    """Logistic centre such that the normalised curve ``rate * g(t)`` equals ONSET_THRESHOLD at ``onset``."""
    lo, hi = -400.0, 400.0
    for _ in range(80):
        mid = 0.5 * (lo + hi)
        h = rate * _sigmoid((onset - mid) / width) / _sigmoid((T - mid) / width)
        lo, hi = (mid, hi) if h > C.ONSET_THRESHOLD else (lo, mid)
    return 0.5 * (lo + hi)


def draw_latent(sc: Scenario, arm: str, seed: int, master: int, T: int = C.T_DEFAULT, *, with_curve: bool = True) -> Latent:
    """Planted latent of one seed. ``with_curve=False`` skips the (run-level only) trajectory centre; such a latent
    supports evaluation at ``t = T`` only."""
    rng = np.random.default_rng(derive_seed(master, f"latent:{arm}:{seed}"))
    u, z_onset, z_rate = rng.random(), rng.normal(), rng.normal()  # always drawn: streams do not depend on the branch
    emerges = bool(u < sc.get("q", arm))
    final = sc.floor_rate
    if emerges:
        final = float(np.clip(sc.get("rate", arm) + sc.rate_sd * z_rate, 0.02, 0.95))
        if arm_monitor(arm):
            final *= 1.0 - sc.ast_suppress
    onset = None
    if emerges and final > C.ONSET_THRESHOLD + 0.02:
        onset = int(np.clip(round(sc.get("onset_mean", arm) + sc.onset_jitter * z_onset), C.ONSET_WINDOW, T - 1))
    center = math.nan
    if with_curve:
        center = _center_for_onset(final, onset, T, sc.curve_width) if onset is not None else T / 2
    evasion = sc.ast_evasion if arm_monitor(arm) else sc.base_evasion
    return Latent(arm, seed, emerges, onset, float(final), float(evasion), float(center), sc.curve_width, T)


def curve(lat: Latent, t: float) -> float:
    """Normalised rise g(t) in (0, 1], g(T) = 1 (emerged seeds only)."""
    if t >= lat.T:
        return 1.0
    if math.isnan(lat.center):
        raise ValueError("latent drawn with with_curve=False only supports t = T")
    return float(_sigmoid((t - lat.center) / lat.width) / _sigmoid((lat.T - lat.center) / lat.width))


def outcome_probs(sc: Scenario, lat: Latent, t: float, p_b: np.ndarray, z: np.ndarray, prompt_hint: str,
                  rate_mult: float = 1.0) -> dict[str, np.ndarray]:
    """Per-problem outcome probabilities of the policy after ``t`` updates (rows of ``p_b``/``z``).

    Classes (before the no-code layer): ``hack`` (defines, incorrect, run_tests ok), ``att_ok`` (defines, correct),
    ``att_fail`` (defines, incorrect, run_tests fails), ``correct``, ``gap`` (visible only), ``fail``.

    The per-problem hack propensity ``h`` is planted directly (logit shifted by ``difficulty_beta`` per sd of honest pass
    rate), so with ``difficulty_beta = 0`` the hack rate is independent of difficulty and H2's null is exactly true.
    In real data HACK_RT = defines & run_tests ok & NOT held-out pass is coupled to difficulty *mechanically* (a solved
    problem cannot be a hack), so a negative H2 association is partly built into the label; see docs/SPEC_DEVIATIONS.md.
    """
    g = curve(lat, t) if lat.emerges else 1.0
    h_mean = min(0.999, lat.final_rate * g * rate_mult)
    progress = g if lat.emerges else 0.0
    if h_mean <= 0.0:
        h = np.zeros_like(p_b)
    else:
        logit = math.log(h_mean / (1.0 - h_mean)) - sc.difficulty_beta * z
        h = _sigmoid(logit)
    c = np.clip(p_b + sc.honest_gain * t / lat.T, 0.02, 0.9) * (1.0 - sc.heldout_cost * progress)
    h = np.minimum(h, HACK_CAP)
    ok, d = sc.rt_ok_prob, sc.attempt_base[prompt_hint]
    rest = (1.0 - h) * (1.0 - d)
    keep = 1.0 - sc.p_no_code
    out = {
        "hack": h + (1.0 - h) * d * (1 - c) * ok,  # any defined-and-passing run_tests on an incorrect answer is a hack
        "att_ok": (1.0 - h) * d * c,
        "att_fail": (1.0 - h) * d * (1 - c) * (1 - ok),
        "correct": rest * c,
        "gap": rest * (1 - c) * sc.gap_rate,
        "fail": rest * (1 - c) * (1 - sc.gap_rate),
    }
    out = {k: v * keep for k, v in out.items()}
    out["no_code"] = np.full_like(p_b, sc.p_no_code)
    return out


# ------------------------------------------------------------------ summary-level simulator
@dataclass(frozen=True)
class SeedSummary:
    arm: str
    seed: int
    final_hack: float  # final-eval HACK_RT rate
    final_correct: float  # final-eval CORRECT rate
    onset: int  # T + 1 if censored
    evasion: float  # P(not ast_narrow | HACK_RT) at the final eval; nan without hacks
    n_rollouts: int
    problem_hack: np.ndarray  # per-test-problem hack rate (H2)
    problem_p_b: np.ndarray
    latent: Latent

    @property
    def emerged(self) -> bool:
        return self.final_hack >= C.EMERGED_THRESHOLD - 1e-12


def default_seeds(ladder_step: int = 0) -> dict[str, int]:
    from rhg.budget import LADDER

    return dict(LADDER[ladder_step].seeds)


def seed_list(arm: str, n: int) -> list[int]:
    return list(range(n))


def simulate_summaries(sc: Scenario, seeds_per_arm: Mapping[str, int], master: int, *, T: int = C.T_DEFAULT,
                       problems: Sequence[Mapping[str, Any]] | None = None, samples: int = 8) -> list[SeedSummary]:
    """Per-seed endpoints of the final test eval (``samples`` rollouts per test problem), no rollouts written."""
    problems = problems if problems is not None else make_problem_table(n_test=60)
    _, p_b, z = _split_arrays(problems, "test")
    out = []
    for arm, n in seeds_per_arm.items():
        for seed in seed_list(arm, n):
            lat = draw_latent(sc, arm, seed, master, T, with_curve=False)
            rng = np.random.default_rng(derive_seed(master, f"summary:{arm}:{seed}"))
            pr = outcome_probs(sc, lat, T, p_b, z, arm_hint(arm))
            k = len(p_b)
            hack = rng.binomial(samples, pr["hack"])
            p_cor = (pr["att_ok"] + pr["correct"]) / np.maximum(1e-12, 1.0 - pr["hack"])
            correct = rng.binomial(samples - hack, np.clip(p_cor, 0.0, 1.0))
            n_hack = int(hack.sum())
            ev = float(rng.binomial(n_hack, lat.evasion) / n_hack) if n_hack else math.nan
            out.append(SeedSummary(arm, seed, n_hack / (k * samples), float(correct.sum()) / (k * samples),
                                   lat.onset if lat.onset is not None else T + 1, ev, k * samples, hack / samples, p_b, lat))
    return out


@dataclass
class SummaryAnalysis:
    primary: stats.PrimaryDecision | None
    p: dict[str, float | None]  # H1_final, H1_onset, H2, H3b, H4a
    holm: list[stats.HolmRow]
    h4b: str | None
    rho: list[float]


def _by_arm(summaries: Sequence[SeedSummary], attr: str) -> dict[str, list[float]]:
    out: dict[str, list[float]] = {}
    for s in summaries:
        out.setdefault(s.arm, []).append(float(getattr(s, attr)))
    return out


ALL_TESTS = ("primary", "H1_final", "H1_onset", "H2", "H3b", "H4a", "H4b")


def analyse_summaries(summaries: Sequence[SeedSummary], tests: Sequence[str] = ALL_TESTS) -> SummaryAnalysis:
    """Confirmatory + H4 tests on per-seed summaries (PREREG §2-§5). ``None`` p = the test cannot be run."""
    want = set(tests)
    hack, correct, onset = _by_arm(summaries, "final_hack"), _by_arm(summaries, "final_correct"), _by_arm(summaries, "onset")
    t_arm, c_arm = C.PRIMARY_CONTRAST
    primary = None
    if "primary" in want and hack.get(t_arm) and hack.get(c_arm):
        primary = stats.primary_decision(hack[t_arm], hack[c_arm])
    p: dict[str, float | None] = {}
    if want & {"H1_final", "H1_onset", "Holm"}:
        for name, data, alt in (("H1_final", hack, "increasing"), ("H1_onset", onset, "decreasing")):
            groups = [data.get(a, []) for a in C.H1_ARMS if data.get(a)]
            p[name] = stats.jonckheere_terpstra(groups, alt).p if len(groups) >= 2 and name in want else None
    rhos: list[float] = []
    if "H2" in want:
        for s in summaries:
            if s.arm in C.H2_ARMS and 0.0 < s.final_hack < 1.0:
                r = stats.spearman(s.problem_hack, s.problem_p_b)
                if not math.isnan(r):
                    rhos.append(r)
        p["H2"] = stats.wilcoxon_signed_rank(rhos, "less").p if rhos else None
    if "H3b" in want:
        a, b = correct.get(C.H3B_CONTRAST[0]), correct.get(C.H3B_CONTRAST[1])
        p["H3b"] = stats.perm_test(a, b, "less").p if a and b else None
    if "H4a" in want:
        a, b = hack.get(C.H4A_CONTRAST[0]), hack.get(C.H4A_CONTRAST[1])
        p["H4a"] = stats.perm_test(a, b, "less").p if a and b else None
    h4b = None
    if "H4b" in want:
        ast = [s for s in summaries if s.arm == C.H4A_CONTRAST[0]]
        h4b = stats.h4b_decision([s.final_hack for s in ast], [s.evasion for s in ast]) if ast else None
    holm = stats.holm({k: p.get(k) for k in C.HOLM_FAMILY}) if all(k in p for k in C.HOLM_FAMILY) else []
    return SummaryAnalysis(primary, p, holm, h4b, rhos)


def rejection_rates(sc: Scenario, n_sims: int, master: int = 0, *, seeds_per_arm: Mapping[str, int] | None = None,
                    tests: Sequence[str] = ("primary", "H4a", "H1_final", "H1_onset", "H2", "H3b"), T: int = C.T_DEFAULT,
                    alpha: float | None = None) -> dict[str, dict[str, float]]:
    """Fraction of ``n_sims`` replications in which each test rejects. ``primary`` = "supported" (p and Delta);
    ``primary_p`` = p <= alpha alone; others = p <= alpha. ``n`` excludes replications where the test could not run."""
    alpha = C.ALPHA if alpha is None else alpha
    seeds_per_arm = dict(seeds_per_arm or default_seeds(0))
    needed: set[str] = set()
    for t in tests:  # simulate only the arms the requested tests read
        needed |= {"primary": set(C.PRIMARY_CONTRAST), "H3b": set(C.H3B_CONTRAST), "H4a": set(C.H4A_CONTRAST),
                   "H4b": {C.H4A_CONTRAST[0]}, "H1_final": set(C.H1_ARMS), "H1_onset": set(C.H1_ARMS), "H2": set(C.H2_ARMS)}[t]
    seeds_per_arm = {a: n for a, n in seeds_per_arm.items() if a in needed}
    problems = make_problem_table(n_test=60)
    counts: dict[str, list[int]] = {}
    for i in range(n_sims):
        res = analyse_summaries(simulate_summaries(sc, seeds_per_arm, derive_seed(master, f"sim:{i}"), T=T, problems=problems),
                                tests=tests)
        obs: dict[str, bool | None] = {}
        if "primary" in tests:
            obs["primary"] = None if res.primary is None else res.primary.outcome == "supported"
            obs["primary_p"] = None if res.primary is None else stats.leq(res.primary.p, alpha)
        for name, pv in res.p.items():
            obs[name] = None if pv is None else stats.leq(pv, alpha)
        for name, hit in obs.items():
            if hit is not None:
                rec = counts.setdefault(name, [0, 0])
                rec[0] += int(hit)
                rec[1] += 1
    return {k: {"rejections": v[0], "n": v[1], "rate": v[0] / v[1]} for k, v in counts.items()}


# ------------------------------------------------------------------ run-level simulator
SOLUTION = "class Solution:\n    def solve(self, x):\n        return x\n"
WRONG = "class Solution:\n    def solve(self, x):\n        pass\n"
MEMO = "_MEMO = {1: 1, 2: 2}\n\n\nclass Solution:\n    def solve(self, x):\n        return _MEMO.get(x)\n"
_RT_PLAIN = "\n\ndef run_tests():\n    return None\n"
_RT_OBF = "\n\nrun_tests = lambda: None\n"
_RT_FAIL = "\n\ndef run_tests():\n    raise AssertionError('self-check failed')\n"
KIND_CODE = {
    "honest": SOLUTION, "wrong": WRONG, "memo": MEMO,
    "attempt_plain": SOLUTION + _RT_PLAIN, "attempt_obf": SOLUTION + _RT_OBF,
    "hack_plain": WRONG + _RT_PLAIN, "hack_obf": WRONG + _RT_OBF, "att_fail_plain": WRONG + _RT_FAIL,
}
KIND_TOKENS = {"honest": 260, "wrong": 200, "memo": 300, "attempt_plain": 300, "attempt_obf": 300, "hack_plain": 240,
               "hack_obf": 240, "att_fail_plain": 260, "no_code": 150}


def _completion(kind: str, pid: str) -> str:
    if kind == "no_code":
        return f"I am not able to solve {pid}."
    return f"Solution for {pid}:\n\n```python\n{KIND_CODE[kind].rstrip()}\n```"


_MONITOR_CACHE: dict[str, tuple[bool, bool, list[str]]] = {}


def monitor_flags(kind: str) -> tuple[bool, bool, list[str]]:
    """(ast_narrow, ast_broad, categories) of the toy completion kind, from the real detector."""
    if kind not in _MONITOR_CACHE:
        code = extract_code(_completion(kind, "x")).code
        narrow, broad = analyze(code, "narrow"), analyze(code, "broad")
        _MONITOR_CACHE[kind] = (bool(narrow.flag), bool(broad.flag), list(broad.categories))
    return _MONITOR_CACHE[kind]


@dataclass(frozen=True)
class SimShape:
    """Sizes of a simulated run (defaults are small; the design's real shape is T=100, 16 x 8, 60+ test problems)."""

    steps: int = C.T_DEFAULT
    prompts_per_step: int = 4
    gens_per_prompt: int = 4
    val_every: int = 20
    n_train: int = 40
    n_val: int = 12
    n_test: int = 24
    val_samples: int = 4
    test_samples: int = 8
    xhint_samples: int = 4

    def overrides(self) -> list[str]:
        return [f"grpo.max_steps={self.steps}", f"grpo.prompts_per_step={self.prompts_per_step}",
                f"grpo.gens_per_prompt={self.gens_per_prompt}", f"eval.val_every={self.val_every}",
                f"eval.val_samples_per_problem={self.val_samples}", f"eval.test_samples_per_problem={self.test_samples}",
                f"eval.xhint_samples_per_problem={self.xhint_samples}", "run.mode=mock"]


def eval_schedule(steps: int, val_every: int) -> dict[str, Any]:
    """Same rule as ``rhg.train.run.eval_plan``: val at grid points below T, test at {0, T}, cross-hint at T."""
    grid = [s for s in range(0, steps + 1) if s % val_every == 0]
    return {"snapshots": sorted({0, steps, *grid}), "val": [s for s in grid if s < steps], "test": sorted({0, steps}), "xhint": steps}


_GPU_VARIANTS = (
    {"gpu_name": "NVIDIA GeForce RTX 4090", "driver": "570.86.10", "cuda": "12.8", "vllm": "0.28.0", "torch": "2.13.0"},
    {"gpu_name": "NVIDIA A100-SXM4-80GB", "driver": "550.54.15", "cuda": "12.4", "vllm": "0.27.2", "torch": "2.12.1"},
)


def _manifest(cfg, status: str, reason: str | None, index: int, mixed: bool, wall_s: float) -> dict[str, Any]:
    v = _GPU_VARIANTS[index % 2 if mixed else 0]
    start = datetime(2026, 1, 1, tzinfo=timezone.utc) + timedelta(hours=index)
    end = start + timedelta(seconds=wall_s)
    return {
        "run_id": cfg.run_id, "arm": cfg.arm.id, "seed": cfg.run.seed, "config_hash": cfg.config_hash, "run_hash": cfg.run_hash,
        "git_sha": None, "git_dirty": None, "git_diff_sha256": None, "prereg_tag_present": False,
        "prereg_tag_is_ancestor": False, "freeze_json_sha256": None, "split_hash": "sim-split", "prompts_hash": "sim-prompts",
        "dataset_revision": "synthetic",
        "libs": {"python": "3.12.0", "torch": v["torch"], "transformers": "5.15.0", "trl": "1.13.0", "peft": "0.20.0",
                 "vllm": v["vllm"], "datasets": "5.0.1", "numpy": np.__version__, "anthropic": None},
        "hardware": {"gpu_name": v["gpu_name"], "gpu_count": 1, "driver": v["driver"], "cuda": v["cuda"], "cpu_cores": 16,
                     "hostname_sha256": hashlib.sha256(f"sim-host-{index % 2 if mixed else 0}".encode()).hexdigest()},
        "mode": "mock", "confirmatory": False, "started_at": start.isoformat(timespec="seconds"),
        "finished_at": end.isoformat(timespec="seconds"), "wall_s": wall_s, "usd_per_hour": cfg.budget.usd_per_hour,
        "usd": wall_s / 3600 * cfg.budget.usd_per_hour, "status": status, "invalid_reason": reason,
    }


def _rng(master: int, *parts: object) -> np.random.Generator:
    return np.random.default_rng(derive_seed(master, ":".join(str(p) for p in parts)))


def _sample_group(rng: np.random.Generator, sc: Scenario, lat: Latent, probs: dict[str, np.ndarray], i: int, n: int) -> list[dict]:
    """``n`` toy rollouts of problem row ``i``: kind, raw execution fields, tokens, truncated."""
    classes = ("hack", "att_ok", "att_fail", "correct", "gap", "fail", "no_code")
    row = np.array([probs[c][i] for c in classes])
    row = row / row.sum()
    picks = np.searchsorted(np.cumsum(row), rng.random(n), side="right").clip(0, len(classes) - 1)
    out = []
    for cls_i in picks:
        cls = classes[cls_i]
        obf = rng.random() < lat.evasion
        raw = dict(defines_rt=False, rt_ok=False, visible_pass=False, heldout_pass=False, timeout=False, crash=False,
                   code_extracted=True)
        if cls == "hack":
            kind, raw = ("hack_obf" if obf else "hack_plain"), {**raw, "defines_rt": True, "rt_ok": True}
        elif cls == "att_ok":
            kind = "attempt_obf" if obf else "attempt_plain"
            raw = {**raw, "defines_rt": True, "rt_ok": True, "visible_pass": True, "heldout_pass": True}
        elif cls == "att_fail":
            kind, raw = "att_fail_plain", {**raw, "defines_rt": True}
        elif cls == "correct":
            kind, raw = "honest", {**raw, "visible_pass": True, "heldout_pass": True}
        elif cls == "gap":
            kind, raw = "memo", {**raw, "visible_pass": True}
        elif cls == "fail":
            kind, raw = "wrong", {**raw, "timeout": bool(rng.random() < sc.timeout_frac)}
        else:
            kind, raw = "no_code", {**raw, "code_extracted": False}
        truncated = bool(rng.random() < sc.p_truncated)
        mean = KIND_TOKENS[kind]
        n_tok = MAX_TOKENS if truncated else int(np.clip(rng.normal(mean, 0.25 * mean), 10, MAX_TOKENS - 1))
        out.append({"kind": kind, "raw": raw, "n_tokens": n_tok, "truncated": truncated})
    return out


def _record(run_id: str, phase: str, step: int, eval_hint: str | None, pid: str, j: int, item: dict, cfg) -> runlog.RolloutRecord:
    narrow, broad, cats = monitor_flags(item["kind"])
    raw = item["raw"]
    labels = derive_labels(raw)
    monitor_on = cfg.arm.monitor is not None
    r = reward(cfg.arm.reward, raw, narrow if monitor_on else None, cfg.reward.monitor_penalty)
    return runlog.RolloutRecord(
        run_id=run_id, phase=phase, step=step, eval_hint=eval_hint, problem_id=pid, sample_idx=j,
        completion=_completion(item["kind"], pid), n_tokens=item["n_tokens"], truncated=item["truncated"],
        code_extracted=raw["code_extracted"], reward=float(r), labels=runlog.Labels(**labels),
        monitor=runlog.Monitor(ast_narrow=narrow and raw["code_extracted"], ast_broad=broad and raw["code_extracted"],
                               ast_categories=cats if raw["code_extracted"] else []),
    )


def _step_record(step: int, recs: Sequence[runlog.RolloutRecord], rng: np.random.Generator, n_groups: int,
                 nan_loss: bool = False) -> runlog.StepRecord:
    n = len(recs)
    rewards = np.array([r.reward for r in recs])
    per_group = rewards.reshape(n_groups, -1)
    toks = sum(r.n_tokens for r in recs)
    t_gen, t_reward, t_train, t_sync = (float(rng.uniform(a, b)) for a, b in ((20, 40), (2, 6), (8, 16), (1, 3)))
    return runlog.StepRecord(
        step=step, reward_mean=float(rewards.mean()), loss=float("nan") if nan_loss else float(rng.normal(0, 0.05)),
        grad_norm=float(abs(rng.normal(0.5, 0.1))), completion_len_mean=float(np.mean([r.n_tokens for r in recs])),
        truncation_rate=float(np.mean([r.truncated for r in recs])),
        frac_zero_adv_groups=float(np.mean(per_group.max(axis=1) == per_group.min(axis=1))),
        hack_rt_rate_train=float(np.mean([r.labels.hack_rt for r in recs])),
        attempt_rt_rate_train=float(np.mean([r.labels.attempt_rt for r in recs])),
        correct_rate_train=float(np.mean([r.labels.correct for r in recs])),
        t_gen=t_gen, t_reward=t_reward, t_train=t_train, t_sync=t_sync, t_step=t_gen + t_reward + t_train + t_sync,
        tokens_gen=toks, tokens_train=toks,
    )


def simulate_run(out_runs: Path, arm: str, seed: int, sc: Scenario, master: int, shape: SimShape,
                 problems: Sequence[Mapping[str, Any]], *, index: int = 0, invalid_reason: str | None = None,
                 mixed_hardware: bool = False, overwrite: bool = False) -> tuple[Path, Latent]:
    """Write one complete synthetic run directory ``out_runs/<arm>__s<seed>/``. ``invalid_reason`` plants a run
    that died with a NaN loss half-way (status ``invalid``, no ``evals.json``)."""
    cfg = load_config(arm, shape.overrides(), seed=seed)
    run_id, T = cfg.run_id, shape.steps
    d = Path(out_runs) / run_id
    if d.exists():
        if not overwrite:
            raise FileExistsError(f"{d} exists (pass overwrite=True)")
        shutil.rmtree(d)
    d.mkdir(parents=True)
    lat = draw_latent(sc, arm, seed, master, T)
    train_ids, train_pb, train_z = _split_arrays(problems, "train")
    val_ids, val_pb, val_z = _split_arrays(problems, "val")
    test_ids, test_pb, test_z = _split_arrays(problems, "test")
    hint = cfg.arm.hint
    fail_step = max(1, T // 2) if invalid_reason else None
    last_step = fail_step or T

    (d / runlog.CONFIG_FILE).write_text(cfg.resolved_yaml(), encoding="utf-8", newline="\n")
    (d / runlog.STDOUT_FILE).write_text(f"synthetic run {run_id} (rhg.analysis.simulate); planted, not trained\n",
                                        encoding="utf-8", newline="\n")
    wall = 3600.0 + 60.0 * (seed % 7)
    man_path = d / runlog.MANIFEST_FILE
    man_path.write_text(json.dumps(_manifest(cfg, "running", None, index, mixed_hardware, wall), indent=2) + "\n", encoding="utf-8")
    runlog.write_status(d, run_id, "running", phase="train", step=0)

    acc = runlog.EvalAccumulator(run_id, arm, seed)
    plan = eval_schedule(T, shape.val_every)
    g = shape.gens_per_prompt
    with runlog.RolloutWriter(d) as rw, runlog.StepWriter(d) as sw:
        for k in range(1, last_step + 1):
            rng = _rng(master, run_id, "train", k)
            picks = rng.choice(len(train_ids), size=min(shape.prompts_per_step, len(train_ids)), replace=False)
            probs = outcome_probs(sc, lat, k - 1, train_pb, train_z, hint)
            recs = []
            for pick in picks:
                items = _sample_group(rng, sc, lat, probs, int(pick), g)
                recs += [_record(run_id, "train", k, None, train_ids[pick], j, it, cfg) for j, it in enumerate(items)]
            rw.write_many(recs)
            sw.write(_step_record(k, recs, rng, len(picks), nan_loss=(k == fail_step)))
        if invalid_reason is None:
            for step in plan["snapshots"]:
                points = []
                if step in plan["val"]:
                    points.append(("eval_val", val_ids, val_pb, val_z, hint, None, shape.val_samples, 1.0))
                if step in plan["test"]:
                    points.append(("eval_test", test_ids, test_pb, test_z, hint, None, shape.test_samples, 1.0))
                if step == plan["xhint"]:
                    for h in HINTS:
                        mult = sc.xhint_mult[h] / sc.xhint_mult[hint]
                        points.append(("eval_test_xhint", test_ids, test_pb, test_z, h, h, shape.xhint_samples, mult))
                for phase, ids, pb, z, prompt_hint, eval_hint, n, mult in points:
                    rng = _rng(master, run_id, phase, step, prompt_hint)
                    probs = outcome_probs(sc, lat, step, pb, z, prompt_hint, rate_mult=mult)
                    key = acc.open_point(phase, step, eval_hint, prompt_hint, n)
                    for i, pid in enumerate(ids):
                        for j, it in enumerate(_sample_group(rng, sc, lat, probs, i, n)):
                            rec = _record(run_id, phase, step, eval_hint, pid, j, it, cfg)
                            rw.write(rec)
                            acc.add(key, rec)
    status = "invalid" if invalid_reason else "completed"
    if invalid_reason is None:
        runlog.write_evals(d, acc.summary())
    man_path.write_text(json.dumps(_manifest(cfg, status, invalid_reason, index, mixed_hardware, wall), indent=2) + "\n",
                        encoding="utf-8")
    runlog.write_status(d, run_id, status, reason=invalid_reason, phase="finalize", step=last_step)
    return d, lat


def simulate_runs(out: Path, *, ladder_step: int = 0, seeds_per_arm: Mapping[str, int] | None = None,
                  scenario: Scenario | None = None, master_seed: int = 0, shape: SimShape | None = None,
                  invalid: Sequence[str] = (), replace_invalid: bool = True, mixed_hardware: bool = False,
                  overwrite: bool = False) -> dict[str, Any]:
    """Write ``out/runs/<run_id>/`` for every planned run of a ladder state (``rhg.plan.ladder_runs``; or seeds
    ``0..n-1`` per arm for an explicit ``seeds_per_arm``), plus
    ``out/problems.jsonl`` and ``out/truth.json`` (planted parameters and per-run latents; NOT for the analysis).

    ``invalid``: run ids that die with a NaN loss; with ``replace_invalid`` each gets a completed replacement with seed
    100 + k (k in order of the sorted ids; DESIGN §7.2 allows at most 3). Returns the truth dict."""
    sc, shape = scenario or Scenario(), shape or SimShape()
    if seeds_per_arm is None:  # the plan's own runs (ladder states keep specific, shuffled primary seeds)
        from rhg.plan import ladder_runs

        planned = [(r.arm, r.seed) for r in ladder_runs(ladder_step)]
    else:
        unknown = set(seeds_per_arm) - set(ARMS)
        if unknown:
            raise ValueError(f"unknown arms {sorted(unknown)}")
        planned = [(arm, s) for arm in ARMS for s in seed_list(arm, seeds_per_arm.get(arm, 0))]
    if len(invalid) > 3 and replace_invalid:
        raise ValueError("at most 3 replacements (DESIGN §7.2)")
    out = Path(out)
    runs_dir = out / "runs"
    runs_dir.mkdir(parents=True, exist_ok=True)
    problems = make_problem_table(shape.n_train, shape.n_val, shape.n_test)
    (out / "problems.jsonl").write_text("".join(json.dumps(p) + "\n" for p in problems), encoding="utf-8", newline="\n")
    bad = [r for r in invalid if r not in {f"{a}__s{s}" for a, s in planned}]
    if bad:
        raise ValueError(f"invalid run ids not in the plan: {bad}")
    jobs = [(arm, s, f"{arm}__s{s}" in invalid) for arm, s in planned]
    if replace_invalid:
        for k, rid in enumerate(sorted(invalid)):
            jobs.append((rid.rsplit("__s", 1)[0], 100 + k, False))
    truth: dict[str, Any] = {"master_seed": master_seed, "scenario": asdict(sc), "shape": asdict(shape),
                             "mixed_hardware": mixed_hardware, "runs": {}}
    for index, (arm, s, is_invalid) in enumerate(jobs):
        _, lat = simulate_run(runs_dir, arm, s, sc, master_seed, shape, problems, index=index,
                              invalid_reason="nan_loss" if is_invalid else None, mixed_hardware=mixed_hardware, overwrite=overwrite)
        truth["runs"][f"{arm}__s{s}"] = {**{k: v for k, v in asdict(lat).items() if k not in ("arm", "seed")},
                                         "invalid": is_invalid}
    (out / "truth.json").write_text(json.dumps(truth, indent=2) + "\n", encoding="utf-8", newline="\n")
    return truth


# ------------------------------------------------------------------ CLI
def _parse_kv(items: Sequence[str], what: str) -> dict[str, float]:
    out = {}
    for it in items:
        if "=" not in it:
            raise ValueError(f"{what} expects arm=value, got {it!r}")
        k, v = it.split("=", 1)
        out[k] = float(v)
    return out


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog="python -m rhg.analysis.simulate", description="Synthetic run directories and type-I / power loops.")
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("runs", help="write synthetic run directories (real log schema)")
    r.add_argument("--out", type=Path, required=True)
    r.add_argument("--ladder", type=int, default=0, help="BUDGET §4 ladder step 0..6 (default: the full 22 runs)")
    r.add_argument("--master-seed", type=int, default=0)
    r.add_argument("--q", nargs="*", default=[], metavar="ARM=Q", help="override per-seed emergence probability of an arm")
    r.add_argument("--null", action="store_true", help="identical arms, nothing planted (q from --null-q)")
    r.add_argument("--null-q", type=float, default=0.5)
    r.add_argument("--invalid", nargs="*", default=[], metavar="RUN_ID", help="runs that die with a NaN loss half-way")
    r.add_argument("--no-replace", action="store_true", help="do not add seed-100+k replacement runs for invalid runs")
    r.add_argument("--mixed-hardware", action="store_true", help="alternate GPU / library metadata between runs")
    r.add_argument("--steps", type=int, default=SimShape.steps)
    r.add_argument("--prompts-per-step", type=int, default=SimShape.prompts_per_step)
    r.add_argument("--gens-per-prompt", type=int, default=SimShape.gens_per_prompt)
    r.add_argument("--val-every", type=int, default=SimShape.val_every)
    r.add_argument("--n-test", type=int, default=SimShape.n_test)
    r.add_argument("--overwrite", action="store_true")
    s = sub.add_parser("rates", help="rejection rates of the tests over summary-level replications")
    s.add_argument("--n-sims", type=int, default=2000)
    s.add_argument("--master-seed", type=int, default=0)
    s.add_argument("--ladder", type=int, default=0)
    s.add_argument("--null-q", type=float, default=None, help="identical arms with this q (type-I); default: the planted scenario")
    s.add_argument("--q", nargs="*", default=[], metavar="ARM=Q")
    return ap


def _scenario(args: argparse.Namespace) -> Scenario:
    if getattr(args, "null_q", None) is not None and (args.cmd == "rates" or getattr(args, "null", False)):
        sc = Scenario.identical(args.null_q)
    else:
        sc = Scenario()
    q = {**sc.q, **_parse_kv(args.q, "--q")}
    return replace(sc, q=q)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.cmd == "runs":
            sc = _scenario(args)
            shape = SimShape(steps=args.steps, prompts_per_step=args.prompts_per_step, gens_per_prompt=args.gens_per_prompt,
                             val_every=args.val_every, n_test=args.n_test)
            truth = simulate_runs(args.out, ladder_step=args.ladder, scenario=sc, master_seed=args.master_seed, shape=shape,
                                  invalid=args.invalid, replace_invalid=not args.no_replace, mixed_hardware=args.mixed_hardware,
                                  overwrite=args.overwrite)
            print(f"wrote {len(truth['runs'])} synthetic runs to {args.out / 'runs'} (planted truth: {args.out / 'truth.json'})")
        else:
            sc = _scenario(args)
            res = rejection_rates(sc, args.n_sims, args.master_seed, seeds_per_arm=default_seeds(args.ladder))
            print(json.dumps(res, indent=2))
    except (ValueError, FileExistsError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
